apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
    - aescbc:
        keys:
        - name: key1
          secret: lk0cD9Dx76NKL3s7FKFOuQ6ZfX0i0b/QQuxNGZzRf5Q= 
    - identity: {}
