apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod
  name: pod
spec:
  volumes:
  - name: secret1
    secret:
      secretName: secret1
  containers:
  - image: nginx
    name: pod
    env:
    - name: AUTH
      valueFrom:
        secretKeyRef:
          name: secret2
          key: login
    volumeMounts:
    - mountPath: /etc/nginx/authentication
      name: secret1
  dnsPolicy: ClusterFirst
  restartPolicy: Always
