apiVersion: v1
kind: Pod
metadata:
  labels:
    run: accessor
  name: accessor
  namespace: default
spec:
  serviceAccountName: accessor
  containers:
  - image: nginx
    name: accessor
  dnsPolicy: ClusterFirst
  restartPolicy: Always
