apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 172.16.0.2
  bindPort: 6443
nodeRegistration:
  name: cks-master
  ignorePreflightErrors:
  - NumCPU
  imagePullPolicy: IfNotPresent
