apiVersion: v1
kind: Pod
metadata:
  labels:
    run: apache
  name: apache
spec:
  containers:
  - image: httpd
    name: apache
    env:
    - name: SECRET
      value: "5555666677778888"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
