apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helm-controller
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role 
  name: ns-admin
subjects:
- kind: ServiceAccount
  name: helm-controller
  namespace: kube-system
