apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: helm-controller
rules:
- apiGroups:
  - helm.cattle.io
  resources:
  - helmchartconfigs
  - helmcharts
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - secrets
  - configmaps
  verbs:
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - list
  - watch
  - create
  - update
  - escalate
  - bind
- verbs:
  - bind
  - escalate
  nonResourceURLs:
  - "*"
